### ISSUE TITLE
2.0.2 fails to build due to test failures

### ISSUE THREAD

**Issue by sebastic** [metaodi/osmapi#127]
The Debian package for 2.0.2 fails to build due to test failures:

There are several `AttributeError` issues like this:
```
tests/node_test.py F.....FException ignored in: <function OsmApi.__del__ at 0x7feffbd95ab0>
Traceback (most recent call last):
  File "/build/python-osmapi-2.0.2/.pybuild/cpython3_3.10_osmapi/build/osmapi/OsmApi.py", line 166, in __del__
    self.close()
  File "/build/python-osmapi-2.0.2/.pybuild/cpython3_3.10_osmapi/build/osmapi/OsmApi.py", line 179, in close
    if self._changesetauto:
AttributeError: 'OsmApi' object has no attribute '_changesetauto'
```
And several `TypeError` issues like this:
```
=================================== FAILURES ===================================
_______________________ TestOsmApiNode.test_Capabilities _______________________

self = <tests.capabilities_test.TestOsmApiNode testMethod=test_Capabilities>

    def test_Capabilities(self):
        self._session_mock()
    
>       result = self.api.Capabilities()

tests/capabilities_test.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
osmapi/OsmApi.py:229: in Capabilities
    data = self._OsmResponseToDom(data, tag="api", single=True)
osmapi/OsmApi.py:2085: in _OsmResponseToDom
    dom = xml.dom.minidom.parseString(response)
/usr/lib/python3.10/xml/dom/minidom.py:1998: in parseString
    return expatbuilder.parseString(string)
/usr/lib/python3.10/xml/dom/expatbuilder.py:925: in parseString
    return builder.parseString(string)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <xml.dom.expatbuilder.ExpatBuilderNS object at 0x7feffba09660>
string = <Mock name='mock.content' id='140668695524880'>

    def parseString(self, string):
        """Parse a document from a string, returning the document node."""
        parser = self.getParser()
        try:
>           parser.Parse(string, True)
E           TypeError: a bytes-like object is required, not 'Mock'

/usr/lib/python3.10/xml/dom/expatbuilder.py:223: TypeError
----------------------------- Captured stdout call -----------------------------
test_Capabilities
<osmapi.OsmApi.OsmApi object at 0x7feffba0b1f0>
None
[]
```
Full buildlog: [python-osmapi.txt](https://github.com/metaodi/osmapi/files/7593054/python-osmapi.txt)

**Comment by metaodi** [comment]
@sebastic what is the best way to reproduce this? I'm not familiar with the debian package of osmapi. But here on GitHub the tests pass.

**Comment by sebastic** [comment]
If you want to reproduce the package build, set up a cowbuilder chroot and use git-buildpackage, see:

 https://debian-gis-team.pages.debian.net/policy/packaging.html#git-pbuilder

```
# Configure sudo
sudo visudo

# Create cowbuilder choot
sudo cowbuilder --create \
                --distribution=sid \
                --basepath=/var/cache/pbuilder/base-sid.cow

# Get source package
mkdir -p ~/git
cd ~/git
gbp clone https://salsa.debian.org/debian-gis-team/python-osmapi
cd python-osmapi

# Build the package inside the chroot
gbp buildpackage --git-pbuilder
```

To troubleshoot the build, login to the chroot:
```
# Login to the chroot
sudo cowbuilder --login --basepath /var/cache/pbuilder/base-sid.cow --bindmounts ~/git

# Enable sources
sed -i 's/#deb/deb/' /etc/apt/sources.list
apt update

# Install build dependencies
apt build-dep python-osmapi
apt install python3-pytest{,-cov} python3-nose- git-buildpackage quilt pristine-tar

# Build the package
cd /home/<user>/git/python-osmapi
gbp buildpackage
```
Or do this in a Debian unstable VM or container.

**Comment by sebastic** [comment]
The issue also happens with python3.9.

It does not happen when running pytest directly in the source tree.

Might be caused by pybuild only copying the `.py` files to the build tree.

**Comment by sebastic** [comment]
> Might be caused by pybuild only copying the `.py` files to the build tree.

That is the problem, copying the files to the pybuild build directory resolves the issue.

**Comment by metaodi** [comment]
Thanks a lot @sebastic !
